export const BANK_LOAD_STARTED = 'BANK_LOAD_STARTED';
export const BANK_LOAD_SUCCESS = 'BANK_LOAD_SUCCESS';
export const BANK_LOAD_FAILURE = 'BANK_LOAD_FAILURE';

export const BANK_UPDATE_VALUE = 'BANK_UPDATE_VALUE';

export const BANK_SAVE_STARTED = 'BANK_SAVE_STARTED';
export const BANK_SAVE_SUCCESS = 'BANK_SAVE_SUCCESS';
export const BANK_SAVE_FAILURE = 'BANK_SAVE_FAILURE';

export const HEADERS_NEW_SAVING = 'HEADERS_NEW_SAVING';
export const HEADERS_UPDATE_SAVING = 'HEADERS_UPDATE_SAVING';
export const HEADERS_DELETE_SAVING = 'HEADERS_DELETE_SAVING';
export const HEADERS_SWITCH_SAVING = 'HEADERS_SWITCH_SAVING';

export const HEADERS_NEW_INCOME = 'HEADERS_NEW_INCOME';
export const HEADERS_UPDATE_INCOME = 'HEADERS_UPDATE_INCOME';

export const HEADERS_SAVE_STARTED = 'HEADERS_SAVE_STARTED';
export const HEADERS_SAVE_SUCCESS = 'HEADERS_SAVE_SUCCESS';
export const HEADERS_SAVE_FAILURE = 'HEADERS_SAVE_FAILURE';
