import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faCalendarAlt,
  faCheckSquare,
  faSave,
  faSquare,
  faUser,
} from '@fortawesome/free-regular-svg-icons';
import {
  faBackward,
  faChartArea,
  faCheck,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCogs,
  faColumns,
  faEdit,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faForward,
  faInfo,
  faLaptopCode,
  faLightbulb,
  faPiggyBank,
  faSolarPanel,
  faSpinner,
  faTimes,
  faTrashAlt,
  faUniversity,
  faUnlockAlt,
  faUserTie,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faBackward,
  faCalendarAlt,
  faChartArea,
  faCheck,
  faCheckSquare,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCogs,
  faColumns,
  faEdit,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faForward,
  faInfo,
  faLaptopCode,
  faLightbulb,
  faPiggyBank,
  faSave,
  faSolarPanel,
  faSpinner,
  faSquare,
  faTimes,
  faTrashAlt,
  faUniversity,
  faUnlockAlt,
  faUser,
  faUserTie
);
